// <auto-generated />
using System;
using FitCore_API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitCoreAPI.Migrations
{
    [DbContext(typeof(FitCoreDbContext))]
    [Migration("20260429035705_CoachSessionsRelationshipFix")]
    partial class CoachSessionsRelationshipFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitCore_API.Entities.AdminModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserId");

                    b.ToTable("admins", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.Auxiliary.ClientMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("MembershipTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_type_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MembershipTypeId");

                    b.ToTable("client_membership", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.Auxiliary.GroupTrainingSessionClient", b =>
                {
                    b.Property<Guid>("GroupTrainingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_training_session_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.HasKey("GroupTrainingSessionId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("group_training_session_client", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.ClientModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserId");

                    b.ToTable("clients", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.CoachModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location_name");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.HasKey("UserId");

                    b.HasIndex("LocationName");

                    b.ToTable("coaches", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.EquipmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipment_type");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("LocationName");

                    b.ToTable("equipments", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.GroupTrainingSessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("RoomId");

                    b.ToTable("group_training_sessions", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.LocationModel", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("address");

                    b.HasKey("Name");

                    b.ToTable("locations", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.ManagerModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location_name");

                    b.HasKey("UserId");

                    b.HasIndex("LocationName");

                    b.ToTable("managers", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.MembershipTypeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("membership_types", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.OccupiedEquipmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("SessionId");

                    b.ToTable("occupied_equipments", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.PersonalTrainingSessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CoachId");

                    b.HasIndex("RoomId");

                    b.ToTable("personal_trainings_sessions", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.RoomEquipmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipment_type");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationName");

                    b.HasIndex("RoomId");

                    b.ToTable("room_equipments", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.RoomModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location_name");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_type");

                    b.HasKey("Id");

                    b.HasIndex("LocationName");

                    b.ToTable("rooms", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("password_salt");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("FitCore_API.Entities.AdminModel", b =>
                {
                    b.HasOne("FitCore_API.Entities.UserModel", "User")
                        .WithOne("Admin")
                        .HasForeignKey("FitCore_API.Entities.AdminModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCore_API.Entities.Auxiliary.ClientMembership", b =>
                {
                    b.HasOne("FitCore_API.Entities.ClientModel", "Client")
                        .WithMany("ClientMemberships")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCore_API.Entities.MembershipTypeModel", "MembershipType")
                        .WithMany("ClientMemberships")
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("MembershipType");
                });

            modelBuilder.Entity("FitCore_API.Entities.Auxiliary.GroupTrainingSessionClient", b =>
                {
                    b.HasOne("FitCore_API.Entities.ClientModel", "Client")
                        .WithMany("ClientGroupSessions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCore_API.Entities.GroupTrainingSessionModel", "GroupTrainingSession")
                        .WithMany("ClientGroupSessions")
                        .HasForeignKey("GroupTrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("GroupTrainingSession");
                });

            modelBuilder.Entity("FitCore_API.Entities.ClientModel", b =>
                {
                    b.HasOne("FitCore_API.Entities.UserModel", "User")
                        .WithOne("Client")
                        .HasForeignKey("FitCore_API.Entities.ClientModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCore_API.Entities.CoachModel", b =>
                {
                    b.HasOne("FitCore_API.Entities.LocationModel", "Location")
                        .WithMany("Coaches")
                        .HasForeignKey("LocationName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCore_API.Entities.UserModel", "User")
                        .WithOne("Coach")
                        .HasForeignKey("FitCore_API.Entities.CoachModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCore_API.Entities.EquipmentModel", b =>
                {
                    b.HasOne("FitCore_API.Entities.LocationModel", "Location")
                        .WithMany("Equipments")
                        .HasForeignKey("LocationName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FitCore_API.Entities.GroupTrainingSessionModel", b =>
                {
                    b.HasOne("FitCore_API.Entities.CoachModel", "Coach")
                        .WithMany("GroupTrainingSessions")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCore_API.Entities.RoomModel", "Room")
                        .WithMany("GroupTrainingSessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FitCore_API.Entities.ManagerModel", b =>
                {
                    b.HasOne("FitCore_API.Entities.LocationModel", "Location")
                        .WithMany("Managers")
                        .HasForeignKey("LocationName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCore_API.Entities.UserModel", "User")
                        .WithOne("Manager")
                        .HasForeignKey("FitCore_API.Entities.ManagerModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCore_API.Entities.OccupiedEquipmentModel", b =>
                {
                    b.HasOne("FitCore_API.Entities.RoomEquipmentModel", "RoomEquipment")
                        .WithMany("OccupiedEquipment")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCore_API.Entities.GroupTrainingSessionModel", "GroupTrainingSession")
                        .WithMany("OccupiedEquipments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupTrainingSession");

                    b.Navigation("RoomEquipment");
                });

            modelBuilder.Entity("FitCore_API.Entities.PersonalTrainingSessionModel", b =>
                {
                    b.HasOne("FitCore_API.Entities.ClientModel", "Client")
                        .WithMany("PersonalTrainingSessions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCore_API.Entities.CoachModel", "Coach")
                        .WithMany("PersonalTrainingSessions")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCore_API.Entities.RoomModel", "Room")
                        .WithMany("PersonalTrainingSessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coach");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FitCore_API.Entities.RoomEquipmentModel", b =>
                {
                    b.HasOne("FitCore_API.Entities.LocationModel", "Location")
                        .WithMany("RoomEquipments")
                        .HasForeignKey("LocationName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCore_API.Entities.RoomModel", "Room")
                        .WithMany("RoomEquipments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FitCore_API.Entities.RoomModel", b =>
                {
                    b.HasOne("FitCore_API.Entities.LocationModel", "Location")
                        .WithMany("Rooms")
                        .HasForeignKey("LocationName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FitCore_API.Entities.ClientModel", b =>
                {
                    b.Navigation("ClientGroupSessions");

                    b.Navigation("ClientMemberships");

                    b.Navigation("PersonalTrainingSessions");
                });

            modelBuilder.Entity("FitCore_API.Entities.CoachModel", b =>
                {
                    b.Navigation("GroupTrainingSessions");

                    b.Navigation("PersonalTrainingSessions");
                });

            modelBuilder.Entity("FitCore_API.Entities.GroupTrainingSessionModel", b =>
                {
                    b.Navigation("ClientGroupSessions");

                    b.Navigation("OccupiedEquipments");
                });

            modelBuilder.Entity("FitCore_API.Entities.LocationModel", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Equipments");

                    b.Navigation("Managers");

                    b.Navigation("RoomEquipments");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("FitCore_API.Entities.MembershipTypeModel", b =>
                {
                    b.Navigation("ClientMemberships");
                });

            modelBuilder.Entity("FitCore_API.Entities.RoomEquipmentModel", b =>
                {
                    b.Navigation("OccupiedEquipment");
                });

            modelBuilder.Entity("FitCore_API.Entities.RoomModel", b =>
                {
                    b.Navigation("GroupTrainingSessions");

                    b.Navigation("PersonalTrainingSessions");

                    b.Navigation("RoomEquipments");
                });

            modelBuilder.Entity("FitCore_API.Entities.UserModel", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Client");

                    b.Navigation("Coach");

                    b.Navigation("Manager");
                });
#pragma warning restore 612, 618
        }
    }
}
